[package]
name = "lixel"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["cors"] }
axum = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
